# Generated by Django 5.2.3 on 2025-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeagueAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=10)),
                ("riot_id", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("riot_region", models.CharField(max_length=10)),
                ("platform", models.CharField(max_length=10)),
                ("tier", models.CharField(blank=True, max_length=30, null=True)),
                ("rank", models.CharField(blank=True, max_length=5, null=True)),
                ("lp", models.IntegerField(blank=True, null=True)),
                ("games", models.IntegerField(blank=True, null=True)),
                ("wr", models.FloatField(blank=True, null=True)),
                ("wr10", models.FloatField(blank=True, null=True)),
                ("wr20", models.FloatField(blank=True, null=True)),
                ("veteran", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
