/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type MangaDirResponse =
    components["schemas"]["MangaDirResponse"]

export type ImageEntry =
    components["schemas"]["ImageEntry"]

export interface paths {
    "/api/manga/dir/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List folders and images */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MangaDirResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MangaDirResponse */
        MangaDirResponse: {
            /** Folders */
            folders: string[];
            /** Images */
            images: components["schemas"]["ImageEntry"][];
        };
        /** ImageEntry */
        ImageEntry: {
            /** Name */
            name: string;
            /** Relative Path */
            relative_path: string;
            /** Url */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
