/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import { components } from "react-select"
import { z } from "zod";

export type ImageEntry =
    components["schemas"]["ImageEntry"]

export type FileEntry =
    components["schemas"]["FileEntry"]

export type MangaInputDirResponse =
    components["schemas"]["MangaInputDirResponse"]

export type MangaOutputDirResponse =
    components["schemas"]["MangaOutputDirResponse"]

export type DialogueLineResponse =
    components["schemas"]["DialogueLineResponse"];

export type OCRImageResponse =
    components["schemas"]["OCRImageResponse"]

export type OCRRunResponse =
    components["schemas"]["OCRRunResponse"]

export const LatestTTSResponseSchema = z.object({
    status: z.enum(["success", "error"]),
    audio_path: z.string().nullable(),
    error: z.string().nullable(),
})

export type LatestTTSResponse =
    z.infer<typeof LatestTTSResponseSchema>

export interface paths {
    "/api/manga/dir/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List folders and images */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MangaInputDirResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manga/output_dir/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List folders and json files */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MangaOutputDirResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manga/json_file/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load results from JSON file, which is the output from OCR API */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OCRRunResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manga/latest_audio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load LATEST version audio file generated from TTS API */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LatestTTSResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MangaInputDirResponse */
        MangaInputDirResponse: {
            /** Folders */
            folders: string[];
            /** Files */
            files: components["schemas"]["ImageEntry"][];
        };
        /** ImageEntry */
        ImageEntry: {
            /** Name */
            name: string;
            /** Relative Path */
            relative_path: string;
            /** Url */
            url: string;
        };
        /** MangaOutputDirResponse */
        MangaOutputDirResponse: {
            /** Folders */
            folders: string[];
            /** Files */
            files: components["schemas"]["FileEntry"][];
        };
        /** FileEntry */
        FileEntry: {
            /** Name */
            name: string;
            /** Relative Path */
            relative_path: string;
            /** Url */
            url: string;
        };
        /** OCRRunResponse */
        OCRRunResponse: {
            /** Run Id */
            run_id: string;
            /** Images */
            images: components["schemas"]["OCRImageResponse"][];
        };
        /** DialogueLineResponse */
        DialogueLineResponse: {
            /** Id */
            id: number;
            /** Speaker */
            speaker: string;
            /** Gender */
            gender: string;
            /** Emotion */
            emotion: string;
            /** Text */
            text: string;
        };
        /** OCRImageResponse */
        OCRImageResponse: {
            /** Image Id */
            image_id: string;
            /** Image File Name */
            image_file_name: string;
            /** Image Rel Path From Root */
            image_rel_path_from_root: string;
            /** Parsed Dialogue */
            parsed_dialogue: components["schemas"]["DialogueLineResponse"][];
            /** Image Width */
            image_width: number;
            /** Image Height */
            image_height: number;
        };
        /** LatestTTSResponse */
        LatestTTSResponse: {
            /** Status */
            status: string;
            /** Audio Path */
            audio_path: string | null;
            /** Error */
            error: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
