/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
import { z } from "zod"

export type TTSDialogueRequest =
    components["schemas"]["TTSDialogueRequest"]

export const TTSDialogueResponseSchema = z.object({
    status: z.literal("success"),
    audio_path: z.string()
})

export type TTSDialogueResponse =
    z.infer<typeof TTSDialogueResponseSchema>


export interface paths {
    "/tts/from_ocr_json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Tts From Ocr Json
         * @description Accepts an OCR pretty JSON (either via Upload or path) + run ID, returns TTS batch result.
         */
        post: operations["run_tts_from_ocr_json_tts_from_ocr_json_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/result/{tts_runid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tts Result
         * @description Fetch the final tts_output.json for a previous run.
         */
        get: operations["get_tts_result_tts_result__tts_runid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tts Single Line */
        post: operations["tts_single_line_tts_line_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/tune_emotion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * TTS Emotion Tuning
         * @description Manually tune exaggeration and cfg for a specific voice (no emotion mapping or gender).
         */
        post: operations["tts_emotion_tuning_tts_tune_emotion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/dialogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate TTS for one dialogue with versioned path */
        post: operations["tts_dialogue_tts_dialogue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_run_tts_from_ocr_json_tts_from_ocr_json_post */
        Body_run_tts_from_ocr_json_tts_from_ocr_json_post: {
            /** File */
            file?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Ocr Runid */
            ocr_runid: string;
        };
        /** EmotionTuneRequest */
        EmotionTuneRequest: {
            /**
             * Text
             * @example I thought I could trust you… but now, I don’t even know who you are anymore.
             */
            text: string;
            /**
             * Gender
             * @example female
             */
            gender: string;
            /**
             * Emotion
             * @example neutral
             */
            emotion?: string | null;
            /**
             * Speaker Id
             * @example default
             */
            speaker_id: string;
            /**
             * Exaggeration
             * @example 0.5
             */
            exaggeration?: number | null;
            /**
             * Cfg
             * @example 0.5
             */
            cfg?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineRequest */
        LineRequest: {
            /**
             * Text
             * @example I'll protect you.
             */
            text: string;
            /**
             * Gender
             * @example female
             */
            gender: string;
            /**
             * Emotion
             * @example calm
             */
            emotion: string;
            /**
             * Speaker Id
             * @example female_generic
             */
            speaker_id: string;
        };
        /** TTSDialogueRequest */
        TTSDialogueRequest: {
            /** Text */
            text: string;
            /** Gender */
            gender: string;
            /** Emotion */
            emotion: string;
            /** Speaker Id */
            speaker_id: string;
            /** Run Id */
            run_id: string;
            /** Image Rel Path From Root */
            image_rel_path_from_root: string;
            /** Image File Name */
            image_file_name: string;
            /** Dialogue Id */
            dialogue_id: number;
            /**
             * Use Custom Params
             * @default false
             */
            use_custom_params: boolean;
            /** Exaggeration */
            exaggeration?: number | null;
            /** Cfg */
            cfg?: number | null;
        };
        /** TTSDialogueResponse */
        TTSDialogueResponse: {
            /** Status */
            status: string;
            /** Audio Path */
            audio_path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_tts_from_ocr_json_tts_from_ocr_json_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_run_tts_from_ocr_json_tts_from_ocr_json_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tts_result_tts_result__tts_runid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tts_runid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_single_line_tts_line_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_emotion_tuning_tts_tune_emotion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmotionTuneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_dialogue_tts_dialogue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TTSDialogueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTSDialogueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
