/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type Emotion =
    components["schemas"]["Emotion"]
export type EmotionParams =
    components["schemas"]["EmotionParams"]
export type Gender =
    components["schemas"]["Gender"]

export const GENDER_OPTIONS = [
    "female",
    "male",
    "neutral",
] as const

// export type MediaRef =
//     components["schemas"]["MediaRef"]
export type Speaker =
    components["schemas"]["Speaker"]
export type TTSInput =
    components["schemas"]["TTSInput-Input"]
export type TTSOutput =
    components["schemas"]["TTSOutput"]
export type EmotionOptionsOutput =
    components["schemas"]["EmotionOptionsOutput"]

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tts/dialogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate TTS for one dialogue with versioned path */
        post: operations["tts_dialogue_tts_dialogue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tts/emotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate all valid Emotions list to populate DDL */
        get: operations["tts_emotions_tts_emotions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Emotion */
        Emotion: {
            /** Name */
            name: string;
            params: components["schemas"]["EmotionParams"];
        };
        /** EmotionOptionsOutput */
        EmotionOptionsOutput: {
            /** Emotionoptions */
            emotionOptions: components["schemas"]["Emotion"][];
        };
        /** EmotionParams */
        EmotionParams: {
            /** Cfg */
            cfg: number;
            /** Exaggeration */
            exaggeration: number;
        };
        /** Gender */
        Gender: {
            /**
             * Value
             * @enum {string}
             */
            value: "female" | "male" | "neutral";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MediaRef */
        MediaRef: {
            /**
             * Namespace
             * @enum {string}
             */
            namespace: "inputs" | "outputs";
            /** Path */
            path: string;
        };
        /** Speaker */
        Speaker: {
            /** Name */
            name: string;
            /** Wav File */
            wav_file: string;
            gender: components["schemas"]["Gender"];
        };
        /** TTSInput */
        "TTSInput-Input": {
            /** Text */
            text: string;
            gender: components["schemas"]["Gender"];
            emotion: components["schemas"]["Emotion"];
            speaker: components["schemas"]["Speaker"];
            image_ref: components["schemas"]["MediaRef"];
            customSettings?: components["schemas"]["EmotionParams"] | null;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /**
             * Custom Filename
             * @default
             */
            custom_filename: string;
            /**
             * Dialogue Id
             * @default -1
             */
            dialogue_id: number;
        };
        /** TTSInput */
        "TTSInput-Output": {
            /** Text */
            text: string;
            gender: components["schemas"]["Gender"];
            emotion: components["schemas"]["Emotion"];
            speaker: components["schemas"]["Speaker"];
            image_ref: components["schemas"]["MediaRef"];
            customSettings?: components["schemas"]["EmotionParams"] | null;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /**
             * Custom Filename
             * @default
             */
            custom_filename: string;
            /**
             * Dialogue Id
             * @default -1
             */
            dialogue_id: number;
        };
        /** TTSOutput */
        TTSOutput: {
            ttsInput: components["schemas"]["TTSInput-Output"];
            /** Audio Posix Path */
            audio_posix_path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    tts_dialogue_tts_dialogue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TTSInput-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TTSOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_emotions_tts_emotions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionOptionsOutput"];
                };
            };
        };
    };
}
