/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type ImagePreviewOut =
    components["schemas"]["ImagePreviewOut"];

export type DialoguePreviewOut =
    components["schemas"]["DialoguePreviewOut"];


export interface paths {
    "/video/runs/{run_id}/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Previews
         * @description Return preview data (pan offsets + crop boxes) for all images in a run.
         *     This does NOT run ffmpeg or build video.
         */
        get: operations["get_run_previews_video_runs__run_id__previews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/runs/{run_id}/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Video Run
         * @description Trigger actual video generation for a run.
         *     This WILL run ffmpeg and take time.
         */
        post: operations["build_video_run_video_runs__run_id__build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DialoguePreviewOut */
        DialoguePreviewOut: {
            /** Dialogue Id */
            dialogue_id: number;
            /** Dialogue Text */
            dialogue_text: string;
            /** Pan Offset */
            pan_offset: number;
            /** Crop Box */
            crop_box: [
                number,
                number,
                number,
                number
            ];
            /** Bbox Y */
            bbox_y: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagePreviewOut */
        ImagePreviewOut: {
            /** Image Id */
            image_id: string;
            /** Image File Name */
            image_file_name: string;
            /** Image Rel Path From Root */
            image_rel_path_from_root: string;
            /** Previews */
            previews: components["schemas"]["DialoguePreviewOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_run_previews_video_runs__run_id__previews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePreviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_video_run_video_runs__run_id__build_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
