# Generated by Django 5.2.3 on 2025-06-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediahub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="file",
        ),
        migrations.AddField(
            model_name="video",
            name="file_path",
            field=models.TextField(blank=True),
        ),
    ]
